AWSTemplateFormatVersion: 2010-09-09
Description: main stack

Resources: 
  # VPCStack
  # VPC（仮想プライベートクラウド）を作成。
  # 必要なパブリックサブネット、プライベートサブネット、ルートテーブル、インターネットゲートウェイを構築。
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/vpc.yml

  # SecurityGroupStack
  # 必要なセキュリティグループを作成。
  # VPCIDをVPCStackから取得して設定。
  # ALB、EC2、RDS用のセキュリティグループを構成し、ネットワークレベルでのアクセス制御を実現。
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/security-groups.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  # RDSInstanceStack
  # プライベートサブネット内にRDSインスタンスをデプロイ。
  # プライベートサブネットIDとRDS用セキュリティグループIDを取得。
  RDSInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/rds.yml
      Parameters:
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        RdsSecurityGroupId: !GetAtt SecurityGroupStack.Outputs.RdsSecurityGroupId

  # ALBInstanceStack
  # アプリケーションロードバランサー（ALB）とEC2オートスケーリンググループを構築。
  # ALBはトラフィックを複数のEC2インスタンスに分散。
  # オートスケーリンググループはトラフィック量に応じてEC2インスタンス数を動的に調整。
  ALBInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/alb+ec2autoscaling.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        AlbSecurityGroupId: !GetAtt SecurityGroupStack.Outputs.AlbSecurityGroupId
        EC2SecurityGroupId: !GetAtt SecurityGroupStack.Outputs.EC2SecurityGroupId

  # CloudWatchStack
  # オートスケーリンググループ用のCloudWatchアラームを設定。
  # CPU使用率に基づいてEC2インスタンスのスケールアップとスケールダウンをトリガーするアラームを構築。
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/cloudwatch.yml
      Parameters:
        AutoScalingGroupName: !GetAtt ALBInstanceStack.Outputs.AutoScalingGroupName

  # CloudFrontStack
  # CloudFrontディストリビューションを構築。
  # ALBと統合し、コンテンツ配信のパフォーマンスを向上。
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://XXXXXXXXXX.s3.ap-northeast-1.amazonaws.com/template/cloudfront.yml
      Parameters:
        ALBDNSName: !GetAtt ALBInstanceStack.Outputs.ALBDnsName
